language: python
python:
  - "3.8"

branches:
  only:
    - main

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - flake8 tests profile_readme
  - pytest tests

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: main
  local-dir: dist
  verbose: trues